sudo: required
services:
    - docker

before_install:
    - docker build -t am-shb/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true am-shb/docker-react npm run test -- --coverage